### Column names
# Demographic factors
INCOME = "income"
POVERTY_LEVEL = "POVERTY3"
RESIDENCE_METROPOLITAN_DENSITY = "COUTYP4"
AGE_CATEGORY_COL = "CATAG3"
NUMBER_OF_TIMES_MARRIED = "NOMARR2"
IS_MILITARY_VETERAN = "actdever"
HEALTH_SELF_ASSESSMENT = "HEALTH2"
GENDER = "IRSEX"
WORK_SITUATION = "WRKSTATWK2"
RACE = "NEWRACE2"
HOUSEHOLD_SIZE = "IRHHSIZ2"
HAS_PRIVATE_HEALTH_INSURANCE = "irprvhlt"
HAS_MEDICARE = "irmedicr"
HAS_MEDICAID = "iimcdchp"
EDUCATION_CATEGORY = "IREDUHIGHST2"

# Substance use
CIGARETTE_EVER = "cigever"
CIGARETTE_PAST_MONTH = "cigmon"
CRACK_EVER = "crkever"
CRACK_PAST_MONTH = "crkmon"
HEROIN_EVER = "herever"
HEROIN_PAST_MONTH = "hermon"

# The subset of columns to be used for our model
COLUMNS_SUBSET = [
    INCOME,
    POVERTY_LEVEL,
    RESIDENCE_METROPOLITAN_DENSITY,
    AGE_CATEGORY_COL,
    NUMBER_OF_TIMES_MARRIED,
    IS_MILITARY_VETERAN,
    HEALTH_SELF_ASSESSMENT,
    WORK_SITUATION,
    EDUCATION_CATEGORY,
    HOUSEHOLD_SIZE,
    HAS_PRIVATE_HEALTH_INSURANCE,
    HAS_MEDICARE,
    HAS_MEDICAID,
    CIGARETTE_EVER,
    CIGARETTE_PAST_MONTH,
    CRACK_EVER,
    CRACK_PAST_MONTH,
    HEROIN_EVER,
    HEROIN_PAST_MONTH,
]
